### PR TITLE
Transform.RotateAround, Exporter config from template, BuildTasks AfterBuild

### PR DESCRIPTION
**Pull request by Elideb**
The method Transform.RotateAround (Vector3 point, Vector3 axis, float angle), to rotate around an arbitrary point and axis was not implemented.

Added support for AfterBuild in BuildTasks, with the corresponding bat.sample.

Copied the exporter configuration from the template (camera config from #25). Replaced a weird

```
<Convert Namespace="UnityEngine" To="c:"/>
```

with

```
<Convert Namespace="UnityEngine" To="PressPlay.FFWD.Components"/>
```

If there is a reason for that "C:", feel free to reject the pull. I'll undo it and try again =)

### CODE REVIEW

**Comment by Elideb** [comment]
The RotateAround method seems to have some problem rotating cylinders and capsules, because their local rotation is applied in the opposite direction as Unity's. Cubes and planes seem to work fine, and it's hard to tell with spheres (will try texturing one).

Is there any special trickery used when rotation complex meshes? I cannot find a way to fix the issue.

**Comment by Elideb** [comment]
Confirmed non-Unity behaviour of meshes. Anything outside of Unity's plane, cube and sphere exhibits an abnormal rotation, but correct position modification. Even a simple cube exported from 3dsmax behaves differently than cubes from Unity.

**Comment by fehaar** [comment]
It could be an issue in the RotateAround code. I can't remember how that is done. But it sounds very wierd that the problem only exists with exported meshes. We are using a lot of exported meshes in our game, and have not seen any issues with it (we have not used RotateAround though).

Regarding the namespace conversion, it is in thre to save space in the XML files. "c:" is defined as a namespace in the top of the XML file, so it can be used instead of PressPlay.FFWD.Components.

**Comment by Elideb** [comment]
I have finally found (part) of the problem.

In Unity both RotateAround methods receive the axis to rotate around in world coordinates. However, FFWD's implementation of RotateAround (axis, fAngle) and my new RotateAround (point, axis, fAngle) calculate the rotation considering the axis to be local, which it is not. Thus, by not converting the axis from world to local, the resulting rotation is influenced by the objects' rotation.
And, here's the tricky part: all my 3DSMax meshes were imported with a rotation of (-90º, 0, 0). And I had modified the rotation of the capsules, cylinders, etc. that I tried.

The code to fix RotateAround is:

```
    public void RotateAround(Vector3 vector3, float fAngle)
    {
        var quaternion = Microsoft.Xna.Framework.Quaternion.CreateFromAxisAngle(InverseTransformDirection(vector3), Mathf.Deg2Rad * fAngle);
        quaternion.Normalize ();
        _localRotation *= (Quaternion)quaternion;
    }
```

The problem I am having now is that the object's scaling seems to also affect rotation, and I can't find where this could be coming from. As far as I can tell, there is no Quaternion containing the current's gameobject position, scaling and rotation in one place, at least related to the operations I'm using.

Also, Unity's RotateAround behaves funny and I can't seem to imitate it's whacky behaviour. I'll check that once I've figured out how to fix the scaling issues.

**Comment by fehaar** [comment]
I guess you had fixes for this in the merge I just pulled? Great detective work there... Having to imitate wonky behaviour from Unity is just great. :D

**Comment by Elideb** [comment]
Yep, this all works pretty well in the latest batch of fixes. I'm still running some tests to capture fringe behaviors, but RotateAround now emulates Unity as well as I can manage.

**Pull request closed without merging**
